services:
  core:
    profiles: ["core"]
    image: ${CORE_IMAGE}
    container_name: ${CORE_CONTAINER_NAME:-core-blue}
    ports:
      - "${CORE_PORT:-8080}:8080"
    env_file: .env.core
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST:-sofly-redis}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT:-6379}
    networks:
      sofly-net:
        aliases:
          - core
    labels:
      - "prometheus_scrape=true" 
    restart: unless-stopped
    healthcheck:
      # test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  supply:
    profiles: ["supply"]
    image: ${SUPPLY_IMAGE}
    container_name: ${SUPPLY_CONTAINER_NAME:-supply-blue}
    ports:
      - "${SUPPLY_PORT:-8082}:8081"
    env_file: .env.supply
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST:-sofly-redis}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT:-6379}
    networks:
      sofly-net:
        aliases:
          - supply
    labels:
      - "prometheus_scrape=true" 
    restart: unless-stopped
    healthcheck:
      # test: ["CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  sofly-net:
    external: true
