services:
  core:
    build: ./services/travel-core-service
    container_name: sofly-core
    ports:
      - "8080:8080"
    env_file: ./services/travel-core-service/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sofly-postgres:5432/sofly_db
      SPRING_DATASOURCE_USERNAME: sofly_user
      SPRING_DATASOURCE_PASSWORD: sofly_password
      REDIS_HOST: sofly-redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - sofly-net

  supply:
    build: ./services/travel-supply-service
    container_name: sofly_supply
    ports:
      - "8082:8081"
    env_file: ./services/travel-supply-service/.env
    environment:
      REDIS_HOST: sofly-redis
    depends_on:
      redis:
        condition: service_started
    networks:
      - sofly-net

  postgres:
    image: postgres:16-alpine
    container_name: sofly-postgres
    networks:
      - sofly-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sofly_db
      POSTGRES_USER: sofly_user
      POSTGRES_PASSWORD: sofly_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sofly_user -d sofly_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sofly-redis
    networks:
      - sofly-net
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  sofly-net:
    name: sofly-net