version: '3.8'
services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: sofly-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    networks:
      - sofly-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sofly-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_HEAP_OPTS: "-Xmx384m -Xms256m"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

networks:
  sofly-net:
    external: true

# Docker Command
# docker compose -f docker-compose.kafka.yml up -d
