server:
  port: 8081

logging:
  level:
    com.sofly.supply.adapter.outbound.rapidapi: DEBUG
    # TODO: 캐시 디버깅 필요 시에만 TRACE로 변경, 운영 환경에서는 비활성화
    # org.springframework.cache: TRACE

spring:
  application:
    name: travel-supply-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jackson:
    serialization:
      indent_output: true

  output:
    ansi:
      enabled: ALWAYS

springdoc:
  swagger-ui:
    path: /supply/swagger-ui
  api-docs:
    path: /supply/v3/api-docs

google:
  places:
    api-key: ${GOOGLE_PLACES_API_KEY:}
    base-url: ${GOOGLE_PLACES_BASE_URL:https://places.googleapis.com}

app:
  suppliers:
    default: booking

rapidapi:
  api-key: ${RAPIDAPI_KEY:}
  host: ${RAPIDAPI_HOST:booking-com15.p.rapidapi.com}
  base-url: ${RAPIDAPI_BASE_URL:https://booking-com15.p.rapidapi.com}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    export:
      prometheus:
  zipkin:
    tracing:
      endpoint: http://sofly-zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
