version: "3"

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_NO_ANALYTICS: "true"
      DOZZLE_USERNAME: "admin"
      DOZZLE_PASSWORD: "1234"
      DOZZLE_LEVEL: "info"      # 로그 레벨
    restart: unless-stopped
