server:
  port: 8080

spring:
  application:
    name: travel-core-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sofly_db}
    username: ${DB_USER:sofly_user}
    password: ${DB_PASSWORD:sofly_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false
  
  output:
    ansi:
      enabled: ALWAYS

springdoc:
  swagger-ui:
    path: /swagger-ui/service
  api-docs:
    path: /v3/api-docs/service

logging:
  exception-conversion-word: "%wEx{0}"
